### PR TITLE
SSH enhancement

### PR DESCRIPTION
**Pull request by zp4rker**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature/enhancement

**What is the current behavior? (You can also link to an open issue here)**
Fetches hosts only from `~/.ssh/config`

**What is the new behavior (if this is a feature change)?**
Now also fetches hosts from `~/.ssh/known_hosts`

**Additional info:**
Also changed the description from `Ssh host` to `SSH host`

### CODE REVIEW

**Comment by zp4rker** [comment]
added an extra feature: shows host suggestions when `user@` is provided.

**Comment by QuiiBz** [comment]
Looks like there's another issue in the typecheck CI: https://github.com/withfig/autocomplete/runs/4070884655?check_suite_focus=true#step:5:8, could you solve this so we can get this PR merged?

**Comment by zp4rker** [comment]
@QuiiBz I have no idea why its failing because:
a) Tests pass fine if I run locally and
b) I haven't touched the `julia` spec

**Comment by QuiiBz** [comment]
> @QuiiBz I have no idea why its failing because:
> a) Tests pass fine if I run locally and
> b) I haven't touched the `julia` spec

I think you should rebase/merge master to your branch, there are some fixes upstream.

**Comment by zp4rker** [comment]
🤦‍♂️ i was trying to merge with master and completely forgot i didn't merge from upstream

**Review by QuiiBz — APPROVED** [review]
No worries! Thanks a lot for this contribution 🚀

**Pull request merged**
