### PR TITLE
feat: add pacman

### PR DESCRIPTION
**Pull request by clo4**
This is still WIP. `exclusiveOn` and `dependsOn` don't quite work for pacman. We need full "options with options".

### CODE REVIEW

**Comment by fedeci** [comment]
@SeparateRecords using subcommands to describe this kind of options isn't a feasible solution?

**Comment by grant0417** [comment]
@fedeci does saying that is a subcommand currently work, otherwise are you able to impl this?

The cases this would have to cover are:

```
$ pacman -Ss
$ pacman -S --search
$ pacman --sync -s
$ pacman --sync --search
```

**Comment by fedeci** [comment]
It works in the sense that they are correctly suggested and treated like subcommands, but for example `-Ss` wouldn't work

**Comment by grant0417** [comment]
What would we need to do to support the `-Ss` case? That is the primary way `pacman` users would expect the command to work and some other arch utils work that way as well.

**Comment by grant0417** [comment]
Would this be an additional flag on the subcommand or impl be default?

**Comment by SeparateRecords** [comment]
Might be interesting to have a parser directive like `parseSubcommandsAsOptions` which uses the option-parsing logic for subcommands?

**Comment by fedeci** [comment]
I think for the moment `additionalSuggestions` may come to our help to achieve that result easily.
@SeparateRecords `parserDirectives` would apply globally but in some cases we only want it for some options.

**Comment by mschrage** [comment]
@grant0417 worthwhile keeping this open? Less relevant now, since we are not focused on Linux support.

**Comment by brendanfalk** [comment]
Going to close this draft for the moment. Can always re-open. @clo4 Any interest in getting this up and running again?

**Pull request closed without merging**
