### PR TITLE
[BREW] Add outdated command

### PR DESCRIPTION
**Pull request by herrherrmann**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This adds the command `outdated` to the autocompletion specs for `brew`.

**What is the current behavior? (You can also link to an open issue here)**
There’s no autocompletion for the `outdated` command yet.

**What is the new behavior (if this is a feature change)?**
There’s autocompletion for the `outdated` command and all of its options now!

screenshot

**Additional info:**
I have _not_ managed to run `npm run build` without screwing up the code formatting for all files in the `specs` folder, so this PR only contains changes in the `dev/brew.ts` file so far.

### CODE REVIEW

**Comment by mattschrage** [comment]
Hey @herrherrmann! Thanks so much for contributing this. We just updated how we lint the completion specs, so it's possible the new rules conflict with the previous ones. I will look into this. I don't think it is an issue with your setup.

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks for your first contribution! Could you run `npm run build` to generate the JS spec and then push it? We will be good to merge then.

**Comment by herrherrmann** [comment]
@QuiiBz That doesn’t really work yet for me because running `npm run build` changes pretty much _all_ files in the spec folder and seems to use a different indentation/formatting config somehow:

Bildschirmfoto 2021-05-22 um 11 20 55

Any idea what I can do here? I’ve already asked about this [on Slack](https://figcommunity.slack.com/archives/C015ZM6BYK1/p1620927266217600).

**Review by cstrnt — APPROVED** [review]
LGTM

**Pull request merged**
