### PR TITLE
feat: add `nmap`completion spec

### PR DESCRIPTION
**Pull request by jeffersonraimon**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**
This PR introduce the feature **nmap**

### CODE REVIEW

**Review by mschrage — CHANGES_REQUESTED** [review]
Hey @jeffersonraimon, thanks so much for contributing. This is a great start.

I had some questions about the subcommands? I think that they should be options instead, and we will just specify `flagsArePosixNoncompliant` in [`parserDirectives`](https://fig.io/docs/reference/subcommand#parserdirectives). 

Also it seems like there are a few options missing from the spec. https://nmap.org/book/man-briefoptions.html

**Comment by jeffersonraimon** [comment]
> Hey @jeffersonraimon, thanks so much for contributing. This is a great start.
> 
> I had some questions about the subcommands? I think that they should be options instead, and we will just specify `flagsArePosixNoncompliant` in [`parserDirectives`](https://fig.io/docs/reference/subcommand#parserdirectives).
> 
> Also it seems like there are a few options missing from the spec. https://nmap.org/book/man-briefoptions.html

Thanks man, I'm glad for contributing on this awesome project! 
And ok, I'll will change those subcommands to options.

**Comment by fedeci** [comment]
@jeffersonraimon any status update on this?

**Comment by fedeci** [comment]
recheck

**Comment by jeffersonraimon** [comment]
@fedeci 
i will update soon

**Review by brendanfalk — APPROVED** [review]

**Review by mschrage — APPROVED** [review]

**Pull request merged**
