### PR TITLE
feature: implement shadcn-ui autocomplete

### PR DESCRIPTION
**Pull request by jacobparis**
Adds suggestions for the [shadcn/ui](https://ui.shadcn.com/docs/cli) CLI tool

The components to add are autocompleted from the shadcn registry

### CODE REVIEW

**Comment by jacobparis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jacobparis** [comment]
recheck

**Comment by grant0417** [comment]
Hey @jacobparis, sorry but it seems someone else has already made a `shadcn-ui` CLI, not sure if yours has anything different, but if you have any improvements I would be happy to merge.

**Comment by jacobparis** [comment]
> Hey @jacobparis, sorry but it seems someone else has already made a `shadcn-ui` CLI, not sure if yours has anything different, but if you have any improvements I would be happy to merge.

No, we can close this. I'm not sure how #2019 was posted and merged while this one was waiting for review but it's the same feature

**Pull request closed without merging**
