### PR TITLE
feat: add xargs completion spec

### PR DESCRIPTION
**Pull request by SeparateRecords**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature: completion spec for `xargs`

**Additional info:**
This is BSD xargs (since Fig is macOS only right now) - a port to Linux, where GNU is the norm, would require changing this.

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
According to [this](https://man7.org/linux/man-pages/man1/xargs.1.html) man page there are some long-option aliases, can you add those?

**Comment by SeparateRecords** [comment]
> According to [this](https://man7.org/linux/man-pages/man1/xargs.1.html) man page there are some long-option aliases, can you add those?

There are in the GNU version, but there aren't on macOS since it uses modified BSD programs (which is closer to the POSIX spec): https://opensource.apple.com/source/shell_cmds/shell_cmds-149/xargs/xargs.c.auto.html

The GNU and BSD versions share a subset of options.

**Comment by fedeci** [comment]
That's something that should be solved.

**Comment by SeparateRecords** [comment]
So to clarify, are you saying to remove non-POSIX options that _do_ exist on macOS or add GNU extensions that _don't_ exist on macOS? I think, given that Fig currently only supports macOS, it's better to leave it as-is.

Looking at precedent, the [`ls` spec](https://github.com/withfig/autocomplete/blob/master/dev/ls.ts) doesn't include the GNU long options ([Linux man page](https://man7.org/linux/man-pages/man1/ls.1.html)), same thing with `cp`. Haven't checked any others.

**Comment by fedeci** [comment]
I mean to fix it a deeper level beginning to allow commands/options...etc to be specific for some platforms
/cc @mschrage

**Comment by SeparateRecords** [comment]
Agreed - I think it would be good to have a plan in place now for platform-specific completions, since that will have to be dealt with at some point. If we cross that bridge now, it'll be a lot easier.

I'm happy to either wait with this PR until there's a solution in place, or to take on the burden of updating it later.

**Comment by QuiiBz** [comment]
> I mean to fix it a deeper level beginning to allow commands/options...etc to be specific for some platforms

 We're only focusing on macOS for now, but that's definitely something that will be implemented in the future, as Fig will be available on others platforms.

Based on your initial comment @SeparateRecords, this spec is BSD-compliant, so it's all fine!

**Comment by SeparateRecords** [comment]
Fixed a minor wording issue that was nagging at me. Ready for review any time :)

**Comment by SeparateRecords** [comment]
Thanks for the input @mschrage! I think that would definitely work, some sugar over that would be lovely. I see #418 is open - I'll leave some thoughts over there :)

**Review by QuiiBz — APPROVED** [review]
LGTM, thanks a lot for this spec 🚀

**Pull request merged**
