### PR TITLE
feat(npm): add icons

### PR DESCRIPTION
**Pull request by samdenty**
https://user-images.githubusercontent.com/13242392/209882789-099cd123-6f1c-4ad4-a067-fbc0d697b653.mp4

### CODE REVIEW

**Comment by samdenty** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brendanfalk** [comment]
This looks awesome. We should merge in asap. Before we do, things we need to do:
- [ ] Speed up icon API (currently runs a little slow)
- [ ] Update Fig schema to specific a fallback icon in the `icon` prop
- [ ] Get images to preserve aspect ratio


image

image

**Comment by samdenty** [comment]
Happy new year!

I've sped up the API, and it's now as fast as the github API.

https://user-images.githubusercontent.com/13242392/210158121-ee84d8e8-be85-4295-811c-97a9c31f78fd.mp4

All icons are cached permanently after first lookup, so subsequent requests will always be fast

**Review by AlanSyue — APPROVED** [review]
LGTM

**Comment by grant0417** [comment]
Looks like the site is offline, also would not like to add unnecessary 3p dependencies for images, would leak our user's data to you for what CLIs they are using.

**Pull request closed without merging**
