### PR TITLE
feat: `pkill` spec

### LINKED ISSUE #1540: [pkill] missing spec

### PR DESCRIPTION
**Pull request by mrhappyma**
Added spec for `pkill`
closes #1540 

*i don't understand half these options lol*

### CODE REVIEW

**Comment by mrhappyma** [comment]
Linter fails at prettier for code spec, I didn't commit the formatted version of that intentionally.

**Comment by SeparateRecords** [comment]
@mrhappyma don't worry about the linter failing, you can also run `git checkout master; git pull; git checkout add-pkill; git merge master` to fix (fix is on main)

**Comment by mrhappyma** [comment]
Turns out GitHub had a button for it 😆

**Review by SeparateRecords — APPROVED** [review]
Looks good! Could make a generator for the argument but we can handle that in a follow up later on, just having the completions for now is great

**Pull request merged**
