### PR TITLE
feat: add Wing completion spec

### PR DESCRIPTION
**Pull request by itaikeren**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add new autocompletion spec for [Wing](https://www.winglang.io/) CLI

**What is the current behavior? (You can also link to an open issue here)**
N/A

**What is the new behavior (if this is a feature change)?**
Autocomplete for Wing CLI

**Additional info:**
[Wing website](https://www.winglang.io/)

### CODE REVIEW

**Comment by ShaiBer** [comment]
Hey @itaikeren happy to see you here :)

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by fedeci** [comment]
recheck

**Comment by fedeci** [comment]
recheck

**Pull request merged**
