### PR TITLE
feat(minectl): update spec

### PR DESCRIPTION
**Pull request by dirien**
PR generated automatically from push-to-fig-autocomplete-action.

### CODE REVIEW

**Comment by fedeci** [comment]
Great! @dirien, what integration are you using?

**Comment by dirien** [comment]
Hi @fedeci,

i tried the [Push To Autocomplete Action](https://fig.io/docs/guides/integrating/push-to-autocomplete-action#push-to-autocomplete-action) and I can see that all the feedback from the PR #1435 got removed.

Is there something I do wrong?

**Comment by fedeci** [comment]
That's why I was asking which framework is minectl using.
To understand what's wrong here I need to explain how the merge tool works:
- Each CLI framework integration is capable of generating a determined set of fig schema properties.
- The merge tool that we use to merge the old spec with the new one needs to know which fig schema properties are generated by the integration and which are not, so we created presets for our first-party integrations. When merging it uses as a base the new spec and as diff the old one. In the resulting spec we will have all properties automatically generated (from the new spec so the old ones gets overridden) and all the properties from the old spec that are not automatically generated.

The problem here is likely that the integration used can generate the `template` property (the merge tool knows it from the preset) but the CLI framework is lacking some config that associates those args to a file.

e.g. for commander we print `template: "filepaths"` only when the argument is `<file>|[file]`.

**Comment by dirien** [comment]
Thanks @fedeci for the explanation! Do you have an example using `cobra`? So I can see how to label the arguments correctly in the code.

I created several PRs for fig support in other cli tools too (goreleaser, cosign) and maybe I have to see what I need to do in my `minectl` cli before continue the work there

**Comment by fedeci** [comment]
@dirien this is the line we use to detect if a filepaths template is used. https://github.com/withfig/autocomplete-tools/blob/94f003f2ede44499f6160b4857167be99a26fe52/integrations/cobra/main.go#L170

**Comment by dirien** [comment]
Close draft for new PR

**Pull request closed without merging**
