### PR TITLE
feat: add `firefox` spec

### PR DESCRIPTION
**Pull request by mrhappyma**
I was messing around a bit and accidentally discovered that there's a Firefox CLI. Huh. Here's a spec for it.

Only a draft because of one thing: how should I do options for the `--start-debugger-server`? The options are `[ <port> | <path> ]`, but I don't see any way to use something like `exclusiveOn` for arguments. This has got to have come up before, right?

### CODE REVIEW

**Comment by SeparateRecords** [comment]
> The options are [ <port> | <path> ], but I don't see any way to use something like exclusiveOn for arguments

When suggesting two mutually exclusive arguments you can give suggestions for both! No need for exclusiveOn there.

```ts
args: {
  name: "port or path",
  template: "filepaths",
  generators: {
    // Needs to trigger on every keystroke
    trigger: () => true,

    // Suggest current token if it's a port number
    custom: (tokens) => {
      const finalToken = tokens[tokens.length-1];
      const port = Number(finalToken);
      if (Number.isNaN(port)) return [];
      if (!Number.isInteger(port)) return [];
      if (port < 0 || port > 65535) return [];
      return [{ name: finalToken, description: "Port number" }];
    },
  },
},

```

**Review by mschrage — APPROVED** [review]
Looks good to me!

**Comment by mschrage** [comment]
@SeparateRecords love this port generator! We could add this to [@fig/autocomplete-generators](https://github.com/withfig/autocomplete-tools/tree/main/generators/src) package?

**Comment by SeparateRecords** [comment]
> We could add this to [@fig/autocomplete-generators](https://github.com/withfig/autocomplete-tools/tree/main/generators/src) package?

If there are more specs that need it, I think it would make sense to do this! Reason I wrote the generator for it because the arg is also suggesting filepaths, so if you're writing a port number we don't want that getting in the way. For most port args I don't think that's necessary, but if we want to include it as a little visual sugar I wouldn't be against it :)

**Pull request merged**
