### PR TITLE
feat: add `futurerestore` completion spec

### PR DESCRIPTION
**Pull request by ssalggnikool**
feat: Also add `-C`, `--clean-fakefs` to palera1n completion spec

### What is futurerestore?
Futurerestore is an idr (idevicerestore) wrapper, used for restoring to signed & unsigned firmware and software for Apples devices. 

Github: https://github.com/futurerestore/futurerestore

### CODE REVIEW

**Comment by ssalggnikool** [comment]
recheck

**Comment by grant0417** [comment]
Hey, can you fix the issues from the linter?

**Comment by eugolonom** [comment]
> Hey, can you fix the issues from the linter?

I've done it hopefully, but it seems like github is ratelimiting itself for verifying the CLA
Also sorry, I was away for the month and didn't see your reply until now.

**Comment by eugolonom** [comment]
recheck

**Pull request closed without merging**
