### PR TITLE
feat: add bit spec

### PR DESCRIPTION
**Pull request by jfabraxas**
Add support for the bit Cli tool
https://bit.dev/reference/reference/cli-reference

### CODE REVIEW

**Comment by jfabraxas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jfabraxas** [comment]
recheck

**Comment by jfabraxas** [comment]
recheck

**Review by mschrage — APPROVED** [review]
This looks good! Thanks for contributing @jfabraxas.

**Pull request merged**
