### PR TITLE
Adding support for MetricFlow

### PR DESCRIPTION
**Pull request by callum-mcdata**
dbt Labs recently released their first integration with the new Semantic Layer capability of MetricFlow. This adds new autocomplete helpers for the MetricFlow (`mf`) command line tool. 

Documentation: https://docs.getdbt.com/docs/build/about-metricflow

### CODE REVIEW

**Comment by callum-mcdata** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by callum-mcdata** [comment]
recheck

**Comment by grant0417** [comment]
This looks good but can you remove the `yarn.lock` changes?

**Comment by grant0417** [comment]
Sorry, that removed it, can you run `git checkout master -- yarn.lock`

**Comment by callum-mcdata** [comment]
Hey Grant! I actually am gonna close this one out and let the MF team own any autocomplete that they want to add. They've done some changes to the CLI commands and so want to make sure they would be the ones to own/maintain it

**Pull request closed without merging**
