### PR TITLE
feat(pac): Added Power Platform CLI completion spec

### PR DESCRIPTION
**Pull request by rajyraman**
Power Platform CLI is a command line tool from Microsoft https://www.nuget.org/packages/Microsoft.PowerApps.CLI/

### CODE REVIEW

**Comment by rajyraman** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mschrage** [comment]
recheck

**Comment by rajyraman** [comment]
@grant0417 @mschrage - Regarding linting errors the autocomplete JSON is autogenerated based on Microsoft's JSON for pac in pac.doc.json

https://nuget.info/packages/Microsoft.PowerApps.CLI/1.29.6

image

**Comment by grant0417** [comment]
You can run `npm run lint:fix` which should resolve the issues. Otherwise you can add an eslint ignore to ignore the lints for the file.

**Comment by rajyraman** [comment]
@grant0417 - New pac version was released after the PR. I have updated the spec and also ran lint as you suggested.

**Review by grant0417 — APPROVED** [review]
Thanks for the contrib!

**Pull request merged**
