### PR TITLE
Run prettier directly, rather than using ESLint

### PR DESCRIPTION
**Pull request by mattschrage**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Pulls prettier out of ESLint and runs the command separately.
**What is the current behavior? (You can also link to an open issue here)**
prettier is included as a plugin of ESLint

**Additional info:**
ESLint with the prettier plugin was really slow on large files (eg. it took 2h to lint all the `aws` completion specs). Running prettier as a standalone command dramatically [increases performance](https://github.com/prettier/prettier-eslint-cli/issues/89#issuecomment-703478321).

There may be things we can do to improve compatibility: for instance, installing `eslint-config-prettier`. See this [document](https://prettier.io/docs/en/install.html) for more details.

### CODE REVIEW

**Comment by mattschrage** [comment]
Also: the `aws` branch is based of of this because otherwise the pre-commit hooks would time out. (I pushed gcloud using `--no-verify`, so once this is merged in I'll redo that PR as well)

**Comment by cstrnt** [comment]
Any particular reason why the scripts folder and the .github folder are ignored? I would love them to be pretty as well ;)

**Comment by QuiiBz** [comment]
Do you plan to remove the comments in prettier's config?

**Comment by cstrnt** [comment]
While I think the PR is great, I honestly think that we don't need to `.prettierignore` file. I think all files should be formatted in a nice way. Don't you think so?

**Comment by cstrnt** [comment]
Works like a charm with your AWS Branch 😎

**Comment by mattschrage** [comment]
I deleted the `.prettierignore` file. Everything can be pretty @cstrnt.

**Pull request merged**
