### PR TITLE
chore(fig): Update spec to B405

### PR DESCRIPTION
**Pull request by SeparateRecords**
Fixes `internal` subcommand to be properly hidden and aliased

### CODE REVIEW

**Review by fedeci — COMMENTED** [review]
I am starting to change those props today in clap. We should also try to check if the push-to-autocomplete-action correctly works for this spec

**Comment by SeparateRecords** [comment]
> I am starting to change those props today in clap.

🙌 You're amazing!

> We should also try to check if the push-to-autocomplete-action correctly works for this spec

For sure, would be best to dogfood it with our own. Does that block us from merging this first? Should we test on this branch?

**Comment by fedeci** [comment]
I think we will have new feature branches to test the action, let's merge this one first!

**Review by fedeci — APPROVED** [review]
Thanks!

**Pull request merged**
