### PR TITLE
fix(railway): verbose/version shorthands

### PR DESCRIPTION
**Pull request by aleksrutins**
See https://github.com/railwayapp/cliv3/issues/6

### CODE REVIEW

**Comment by aleksrutins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nebulatgs — CHANGES_REQUESTED** [review]
Let's hold off on this until CLIv3 is released

**Comment by aleksrutins** [comment]
The previous configuration was incorrect for cliv2 as well, though - the only thing incompatible with v2 in this version is that the `--version` shorthand.

**Comment by fedeci** [comment]
@nebulatgs please ping me when this is ready to be merged!

**Review by fedeci — APPROVED** [review]
Thanks @aleksrutins!

**Pull request merged**
