### PR TITLE
feat(minectl): update spec

### PR DESCRIPTION
**Pull request by dirien**
PR generated automatically from push-to-fig-autocomplete-action.

### CODE REVIEW

**Review by fedeci — APPROVED** [review]
Thanks!

**Review by grant0417 — CHANGES_REQUESTED** [review]
Once you sign the CLA this is good to merge

**Comment by dirien** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fedeci** [comment]
Thanks!

**Pull request merged**
