### PR TITLE
feat: add git completion spec

### PR DESCRIPTION
**Pull request by VityaSchel**
Adds simple spec for [git-profile](https://github.com/dotzero/git-profile)

### CODE REVIEW

**Comment by VityaSchel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by VityaSchel** [comment]
recheck

**Comment by hloth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hloth** [comment]
recheck

**Comment by VityaSchel** [comment]
сами разберетесь, у меня автокомплит уже работает с моим спеком.

**Review by fedeci — COMMENTED** [review]
Thanks for the PR @VityaSchel! I left two comments to solve. I also need all the committers to have the CLA signed

**Comment by fedeci** [comment]
Also, @VityaSchel can you revert the changes to the `yarn.lock` file, please?

**Pull request closed without merging**
