### PR TITLE
feat: [aws] Add help subcommand 

### PR DESCRIPTION
**Pull request by abhisht51**
added support for 
- [x]  aws help with `isPersistent: true` flag

### CODE REVIEW

**Review by viniciusanchieta — APPROVED** [review]

**Comment by abhisht51** [comment]
@viniciusanchieta can you assist me on how I can go åbout signing CLA

**Comment by grant0417** [comment]
You need to post a comment with only the content like:

`I have read the CLA Document and I hereby sign the CLA`

**Comment by abhisht51** [comment]
`I have read the CLA Document and I hereby sign the CLA`

**Comment by grant0417** [comment]
Here is an example: https://github.com/withfig/autocomplete/pull/2003#issuecomment-1594577871

**Comment by abhisht51** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
