### PR TITLE
feat: add spec for `kafkactl`

### PR DESCRIPTION
**Pull request by mwarkentin**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New autocomplete spec for [`kafkactl`](https://github.com/deviceinsight/kafkactl)

**What is the current behavior? (You can also link to an open issue here)**

No autocomplete

**What is the new behavior (if this is a feature change)?**

Autocomplete

**Additional info:**

Generated with the cobra integration

```diff
diff --git a/cmd/root.go b/cmd/root.go
index 8338d38..d14f459 100644
--- a/cmd/root.go
+++ b/cmd/root.go
@@ -7,6 +7,7 @@ import (
 	"strings"
 
 	"github.com/deviceinsight/kafkactl/internal/env"
+	cobracompletefig "github.com/withfig/autocomplete-tools/integrations/cobra"
 
 	"github.com/deviceinsight/kafkactl/cmd/alter"
 	"github.com/deviceinsight/kafkactl/cmd/attach"
@@ -57,6 +58,7 @@ func NewKafkactlCommand(streams output.IOStreams) *cobra.Command {
 	rootCmd.AddCommand(newCompletionCmd())
 	rootCmd.AddCommand(newVersionCmd())
 	rootCmd.AddCommand(newDocsCmd())
+	rootCmd.AddCommand(cobracompletefig.CreateCompletionSpecCommand())
 
 	// use upper-case letters for shorthand params to avoid conflicts with local flags
 	rootCmd.PersistentFlags().StringVarP(&cfgFile, "config-file", "C", "", fmt.Sprintf("config file. one of: %v", configPaths))

```

Had to manually clean up the generated code: https://gist.github.com/mwarkentin/bceba273eadbca827a52b8dcd85ecf9b

### CODE REVIEW

**Comment by mwarkentin** [comment]
Example of the output in fig: 
image

**Comment by grant0417** [comment]
Thanks for the contribution, are you able to add some generators to it, I see there are places it asks for files and it would be quite useful there!

https://fig.io/docs/reference/generator

**Comment by mwarkentin** [comment]
@grant0417 how does it look now? Seems like my editor reformatted / rewrote a bunch of stuff that was autogenerated previously.

**Comment by mwarkentin** [comment]
I'm also curious if there's a way to build advanced features like generator support into the specs that are generated by the fig frameworks?

**Comment by fedeci** [comment]
> I'm also curious if there's a way to build advanced features like generator support into the specs that are generated by the fig frameworks?

Not at the moment, but there are some handy tools like https://fig.io/docs/guides/integrating/push-to-autocomplete-action that simplify spec updating and allow to keep generators between versions so that they only need to be written once.

**Review by fedeci — APPROVED** [review]
LGTM!

**Comment by fedeci** [comment]
recheck

**Comment by mwarkentin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mwarkentin** [comment]
@fedeci looks like the lint error is not from something in this PR if I'm reading the output correctly.

**Pull request merged**
