### PR TITLE
update git stash

### PR DESCRIPTION
**Pull request by FlowyCoder**
The pull request adds the autocompletion for git stash.

There are still 5 TODO's left that I could not fix.

### CODE REVIEW

**Comment by rolandtshen** [comment]
I pushed a commit to remove the origin option under the fetch subcommand and to fix the merge conflict. Seems like the origin would be covered under arguments that got merged into master.

**Comment by rolandtshen** [comment]
I know there are pending TODOs, but the added stash support with the generator looks and works great! The PR looks ready to merge to me; are you planning on working on those todos in this same PR, or should I go ahead and merge this?

**Comment by FlowyCoder** [comment]
I think you can merge it. In the near future I don't have the time to dive into the Todo's. Maybe another one has a good way to implement them.

**Comment by rolandtshen** [comment]
Great, thanks for your contribution!!

**Pull request merged**
