### PR TITLE
feat: Add ddev spec for DDEV

### PR DESCRIPTION
**Pull request by khalwat**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Spec addition: `ddev` for the [DDEV](https://ddev.com/) local development environment

**What is the current behavior? (You can also link to an open issue here)**

Currently `ddev` is not available

**What is the new behavior (if this is a feature change)?**

Adds the `ddev` spec

**Additional info:**

Leverages the Fig-provided Cobra module for generating the spec directly from the `ddev` command: https://github.com/drud/ddev/pull/4216

### CODE REVIEW

**Comment by SeparateRecords** [comment]
Looks good! Can you run `npm run lint:fix` to fix the linting errors?

**Comment by khalwat** [comment]
Done. FWIW, the output here is coming directly from your own Cobra tool:

https://fig.io/docs/guides/integrating/integrations/cobra

...so if what it outputs isn't passing linting, probably it should be fixed as well?

**Comment by SeparateRecords** [comment]
Agreed! It's not a huge deal because the linting errors can be fixed automatically and will be fixed when using our push to autocomplete CI action, but agreed, it should be as close as possible to the intended output by default.

**Review by SeparateRecords — APPROVED** [review]
Big PR so thank you for making it! Looks good to me but it's >1K lines so I'd like a second pair of eyes too just to make sure I haven't missed anything obvious. There's a couple of things I'd change but given that it's generated automatically most could (should?) be fixed upstream, so I'm not too concerned about that.

**Comment by SeparateRecords** [comment]
cc @fedeci

**Comment by khalwat** [comment]
If there's anything else you need me to do here, just let me know.

**Review by mschrage — APPROVED** [review]
Looks good to me! Thanks for contributing the GitHub action upstream to DDEV as well. 

This means the autocomplete for DDEV will always stay up to date. 🎉

**Comment by khalwat** [comment]
How does it work in terms of an actual release that will be available for people to use?

**Comment by fedeci** [comment]
@khalwat specs are automatically published once they are merged in but, because of caches, (npm registry and our CDN provider) they often need a couple days before being publicly available.

**Pull request merged**
