### PR TITLE
style(eslint): add `no-useless-arrays` rule

### PR DESCRIPTION
**Pull request by fedeci**
With this PR we ensure that when `name` properties of subcommands or options have just one value they are not wrapped in array.

### CODE REVIEW

**Comment by QuiiBz** [comment]
Not sure if this rule is really needed, any thoughts on this @sullivan-sean @cstrnt?

**Comment by fedeci** [comment]
I think that makes specs more readable and less "dirty". It also enhances a common style across the files.

**Comment by mschrage** [comment]
I agree with @fedeci! Nice for this to just be standardized.

**Comment by QuiiBz** [comment]
Alright! Could you resolve the merge conflicts first @fedeci?

**Comment by fedeci** [comment]
I have to [update the rule](https://github.com/withfig/autocomplete/pull/468#issuecomment-898660314) also.

**Comment by fedeci** [comment]
I suggest to review this with whitespace diffs disabled.

**Comment by QuiiBz** [comment]
That's looking amazing! One more merge conflict to resolve @fedeci, and we will be ready to merge!

**Comment by fedeci** [comment]
Just let me know when you are finished merging PRs, so I can rebase once and avoid conflicts popping everywhere :)

**Review by QuiiBz — APPROVED** [review]
LGTM!

**Pull request merged**
