### PR TITLE
gh: Enhance pr create --b

### LINKED ISSUE #868: [gh] pr create option base should provide branch names
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

gh pr create --b

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

when typing `gh pr create --b`  the auto-complete tool should generate branch names as options for the base of my PR

### PR DESCRIPTION
**Pull request by khaledosama999**
Resolves #868﻿

### CODE REVIEW

**Review by fedeci — COMMENTED** [review]
Hey @khaledosama999, why are we suggesting local branches if the PR is create on the remote? The base branch refers to the one in which we are going to merge the PR in.

**Comment by khaledosama999** [comment]
I figured you would merge on the branches that you already have synced locally no problem can replace it by using the remote branches, will do so when I have access to my laptop

**Comment by fedeci** [comment]
Great!

**Comment by khaledosama999** [comment]
@fedeci  Resolves thanks for the feedback

**Review by mschrage — APPROVED** [review]

**Pull request merged**
