### PR TITLE
Enhanced cargo support 🚀

### PR DESCRIPTION
**Pull request by Milo123459**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature!
**What is the current behavior? (You can also link to an open issue here)**
It doesn't implement the things I'm implementing
**What is the new behavior (if this is a feature change)?**
Adds the things I'm implementing, see additional info
**Additional info:**
Hey!
First time contributing here, so go easy!

This PR is upgrading the cargo spec to:
Show completion for cargo installed packages (cargo install)
Give autocomplete for alias' defined in .cargo/config
Parse the alias' and check what commands they run and compare with other commands to not give completion for flags that were already passed

Please suggest other things in the issue. A full todo can be found in the `cargo.ts` file

**DRAFT**

### CODE REVIEW

**Comment by Milo123459** [comment]
Windows sucks

**Comment by QuiiBz** [comment]
Hi, is this PR still in draft?

**Comment by QuiiBz** [comment]
Hi, sorry for the delay. Could you rebase/merge master? There are some conflicts 😅

**Comment by Milo123459** [comment]
Jeez, thats quite a few conflicts..

**Comment by QuiiBz** [comment]
> Jeez, thats quite a few conflicts..

Yes :( I have no ideas why

**Comment by QuiiBz** [comment]
Missclicked, sorry!

**Comment by Milo123459** [comment]
Would it be good if I just made a new PR? This is so bloody annoying.
I blame Windows!

**Comment by QuiiBz** [comment]
> Would it be good if I just made a new PR? This is so bloody annoying. I blame Windows!

Sure! I will re-close this one when you open a new PR

**Comment by fedeci** [comment]
Hey @Milo123459, do you still intend to reopen another PR?

**Comment by Milo123459** [comment]
Not in the near future, no. Sorry.

**Comment by fedeci** [comment]
Don't worry!

**Comment by grant0417** [comment]
I'm going to close this PR, I think all functionality suggested has been integrated into the cargo subcommand. Hopefully we will be on windows soon so you can make more PRs @Milo123459 ;)

**Pull request closed without merging**
