### PR TITLE
feat: add goreleaser spec

### LINKED ISSUE #1095: [goreleaser] Missing spec
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

goreleaser

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

I would like the spec for the popular tool called [goreleaser](https://goreleaser.com/)

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR adds the spec for goreleaser and fixes #1095 

**What is the current behavior? (You can also link to an open issue here)**
-
**What is the new behavior (if this is a feature change)?**
-
**Additional info:**
-

### CODE REVIEW

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by caarlos0** [comment]
Other completions are auto-generated... can we do the same for fig?

Also, fig will read from this repo? If so, what happens with different versions of goreleaser, which might have different flags/docs/etc?

**Comment by dirien** [comment]
@caarlos0 https://fig.io/docs/handbook/versioning-completion-specs you can consider this case during the creation of the Spec.

**Comment by fedeci** [comment]
> Other completions are auto-generated... can we do the same for fig?
> 
> Also, fig will read from this repo? If so, what happens with different versions of goreleaser, which might have different flags/docs/etc?

@caarlos0 
Actually we are working on a set of tools to integrate CLI repos directly with autocomplete. This will support (quite soon):
- automatic generation of specs
- automatic versioning
- automatic pr creation to this repo
Once we are done with the stuff mentioned above I can submit a PR to your CLI repo to get the integration working!

@dirien that kind of versioning is becoming outdated very soon because we are creating a new one and we still need to document it!

**Comment by dirien** [comment]
Wow @fedeci, looking forward for this! As talked on discord @caarlos0, I will keep an eye on the spec for now. When something will change in the commands / flags I will update the spec.

**Comment by fedeci** [comment]
Thanks @dirien!

**Pull request merged**
