### PR TITLE
feat: use `requiresSeparator`

### PR DESCRIPTION
**Pull request by fedeci**
# For reviewers, review it commit by commit because the only really significant one is the first.

### CODE REVIEW

**Comment by SeparateRecords** [comment]
Looks good, couldn't find anything broken or wrong :D

**Comment by fedeci** [comment]
I forgot to say that this needed to wait for the AE develop branch to be merged in main.

**Comment by mschrage** [comment]
Do we need to revert? @fedeci

**Comment by fedeci** [comment]
Nope, I just merged that branch

**Comment by mschrage** [comment]
My bad on the premature merge - thanks for catching that quickly 😅

**Pull request merged**
