### PR TITLE
Add `databricks` cli completion

### PR DESCRIPTION
**Pull request by raymonds-backyard**
This PR adds completion spec for Databricks CLI 0.17.7
https://github.com/databricks/databricks-cli

Generated via click_complete_fig with some tweaks

### CODE REVIEW

**Comment by raymonds-backyard** [comment]
recheck

**Comment by raymonds-backyard** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fedeci** [comment]
@raymonds-backyard what are the tweaks applied?

**Comment by raymonds-backyard** [comment]
> 

Found that there was a few number of subcommands misnamed with an additional suffix appended. An example would be each `table` related subcommand will have a "-table" appended on to it. I think I've missed a few so have to add a few more changes. Would you know of a quicker fix here?

**Comment by raymonds-backyard** [comment]
Will abandon this PR, Databricks is looking to replace their current CLI soon

**Pull request closed without merging**
