### PR TITLE
[npm] add missing aliases

### LINKED ISSUE #593: [npm] options misalignment between `npm i` and `npm install`
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

npm

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

`npm install` and `npm i`

### PR DESCRIPTION
**Pull request by zardoy**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix

closes #593

### CODE REVIEW

**Review by fedeci — APPROVED** [review]
It looks good to me, the next time please check if the "I'd like to work on this" chechbox in the issue is false however🙃

**Comment by zardoy** [comment]
Indeed, I didn't notice that 😨. I don't mind if you close this in favor of something else.

**Comment by fedeci** [comment]
No problem, really. You did a great work!

**Review by QuiiBz — APPROVED** [review]
Thanks a lot for this fix and your first PR 🚀

**Pull request merged**
