### PR TITLE
feat(tar): improve spec

### LINKED ISSUE #962: [tar] missing options
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

tar

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

There's a lot missing from this spec, check out `man tar`

### PR DESCRIPTION
**Pull request by bolshoytoster**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Spec update

**What is the current behavior? (You can also link to an open issue here)**
The spec is incomplete: Closes #962

**Additional Info**
There aren't currently any generators or any 'clusters' (e.g. tar **cfv** a.tar /etc) but I could ad them if wanted.

### CODE REVIEW

**Review by fedeci — COMMENTED** [review]
Thanks! My only concern is that this PR refers to GNU tar, but also BSD tar is available, we should differentiate the specs.
Any ideas @SeparateRecords @mschrage? The eventual solution may also be the same for different CLI tools with the same name.

**Comment by bolshoytoster** [comment]
@fedeci there are also three different versions of BSD tar ([freeBSD tar](https://www.freebsd.org/cgi/man.cgi?query=tar), [netBSD tar](https://man.netbsd.org/tar.1) and [openBSD tar](https://man.netbsd.org/tar.1) (There's also a [busybox tar](https://man.netbsd.org/tar.1))).

**Comment by fedeci** [comment]
Love it! Simplicity is always the key😆

**Comment by mschrage** [comment]
@fedeci my sense is long term, we will use the same approach we do for [versioning CLI tools](https://fig.io/docs/handbook/versioning-completion-specs) (perhaps with some syntactic sugar on top).

A CLI spec will export all of the variants it supports.

When a spec is loaded by the autocomplete-engine, we will check if it has variants. If it does, run `getVariant` to determine which one to load.

We would add a list of variants to autocomplete-types, the `getVariant` function and also we'd modify the `completionSpec` function type definition. 

**autocomplete-types**
```ts
type Variant = "GNU" | "openBSD" | "freeBSD" | "netBSD" | "busybox" ...
```

**tar.ts**
```ts
export variants: Variant[] =  ["GNU", "busybox" ]

export const getVariant = async (executeShellCommand): Variant  => {   
  // execute shell commands on device to determine which variant to use
  const help = await executeShellCommand("tar --help")
  return help.includes("GNU") ? "GNU" : "busybox"
}

const completionSpec: Fig.Spec = (version: string?, variant: Variant?): Fig.Spec => {
   switch (variant) {
     case "GNU":
         return { loadSpec: "gnu/tar"}
     case "busybox"
         return { loadSpec: "busybox/tar"}
   }
};
```

**Review by mschrage — CHANGES_REQUESTED** [review]
I am not sure if the autocomplete engine supports flags that are not prefixed with a hyphen? Other than that, everything looks great!

Any thoughts? @fedeci @sullivan-sean

**Comment by fedeci** [comment]
I think `flagsArePosixNonCompliant` will be enough to handle this case.

**Comment by bolshoytoster** [comment]
@fedeci sorry, I didn't see that in the docs. I can add that now.

**Comment by SeparateRecords** [comment]
Is there something blocking this from being merged? Still stuff that needs to be done?

**Pull request merged**
