### PR TITLE
feat(goctl): add completion spec

### PR DESCRIPTION
**Pull request by anqiansong**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
> feature

**What is the current behavior? (You can also link to an open issue here)**
> None

**What is the new behavior (if this is a feature change)?**
> First pull request for goctl

**Additional info:**
Github Repo: https://github.com/zeromicro/go-zero/tree/master/tools/goctl
Description: A cli tool to generate api, zrpc, model code for [go-zero](https://github.com/zeromicro/go-zero)

### CODE REVIEW

**Review by fedeci — APPROVED** [review]
Thanks, it looks great and we can merge this PR as soon as that file is removed! Did you use any tool to autogenerate the spec?

**Comment by anqiansong** [comment]
I refer to the [doc](https://fig.io/docs/guides/integrating/integrations/cobra) to integrate the fig specification generation into goctl cli, and then generate it through goctl cli

**Comment by fedeci** [comment]
Oh great! I've seen the project is using cobra and we also have [an integration](https://fig.io/docs/guides/integrating/integrations/cobra#fig-autocomplete--cobra) for that CLI framework. Do you think it would be possible to collaborate to have automatically updated goctl specs? ([More infos](https://fig.io/docs/guides/integrating/push-to-autocomplete-action))

**Comment by fedeci** [comment]
I'm merging this in the meanwhile.

**Pull request merged**
