### PR TITLE
Add `swift` spec

### PR DESCRIPTION
**Pull request by dlbuckley**
> **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

### Add spec for `swift` tools.

> **What is the current behavior? (You can also link to an open issue here)**

### No current support.

> **What is the new behavior (if this is a feature change)?**

### All current `swift` commands have ben added.

> **Additional info:**

### There is some possible followup work with some generators, but this covers the basic command interface for now.

### CODE REVIEW

**Comment by dlbuckley** [comment]
I've noticed that I've missed a couple of options. I will add these at some point over the next day or so.

**Comment by dlbuckley** [comment]
I've now added the missing options and this PR should be ready for review.

**Review by import-brain — APPROVED** [review]

**Review by mschrage — CHANGES_REQUESTED** [review]
This looks great! The only thing missing is a [`parserDirective`](https://fig.io/docs/reference/subcommand#parserdirectives) at the root level to inform the parse that `flagsArePosixNoncompliant` since the options start with a single dash.

**Comment by dlbuckley** [comment]
I missed that flag when going though the docs, thank for pointing it out. The change has now been made.

**Review by mschrage — APPROVED** [review]

**Comment by dlbuckley** [comment]
@mschrage It looks like the CI job needs to be kicked off again as it looks like it failed due to an action download issue.

**Comment by fedeci** [comment]
Thanks!

**Comment by kabiroberai** [comment]
I'm a bit late to the party but fwiw it should be possible to automate the generation of specs for all but the root swift[c] subcommand, using the experimental SPM spec generator at https://github.com/withfig/fig-swift-argument-parser. Is it possible to extract subcommands into their own spec files?

**Comment by fedeci** [comment]
@kabiroberai do you mean something like aws subcommands?

**Pull request merged**
