### PR TITLE
feat(nx): add support for project json

### PR DESCRIPTION
**Pull request by ikosta**
The Nx.dev CLI had some changes and the `workspace.json` file is deprecated in Nx.dev and was spliced into multiple `project.json` files a time ago with a migration.

These `project.json` files are everywhere in the repository and has information about the project itself, his targets and the targets configuration.

This script now uses all this information to help fill out the command as comfy as possible.

The old `workspace.json` file is still supported.

### CODE REVIEW

**Comment by ikosta** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/withfig/autocomplete/blob/master/cla/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **Konstantinos Tsanakas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

Also I added the missing email address in my GitHub account.

**Comment by ikosta** [comment]
recheck

**Comment by ikosta** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/withfig/autocomplete/blob/master/cla/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by ikosta** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ikosta** [comment]
recheck

**Review by fedeci — APPROVED** [review]
Thanks @ikosta! This is next-level–polished🔥!

**Pull request merged**
