### PR TITLE
feat: add planter spec

### PR DESCRIPTION
**Pull request by matthew-ia**
Add spec for planter CLI

### CODE REVIEW

**Comment by matthew-ia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by fedeci** [comment]
Hi @matthew-ia, can you run `npm run lint:fix` to fix the linting issues?

**Comment by Manu1400** [comment]
@matthew-ia I don't find the CLI. Is it https://github.com/matthew-ia/planter ?

**Comment by matthew-ia** [comment]
> Hi @matthew-ia, can you run `npm run lint:fix` to fix the linting issues and then committing the files?

For whatever reason, running that command on the old copy of the fork didn't work and flagged a bunch of linting errors across my spec and other specs in `./src/` as well. 

I synced my fork with and that seemed to resolve the linting errors.

**Comment by matthew-ia** [comment]
> @matthew-ia I don't find the CLI. Is it https://github.com/matthew-ia/planter ?

@Manu1400 the CLI is not yet publicly released but I wanted to go ahead and get the autocomplete spec situated and test with my local/private copies.

**Pull request merged**
