### PR TITLE
feat(gh): add custom repo completion

### PR DESCRIPTION
**Pull request by ShawnCockburn**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature && update

**What is the current behavior? (You can also link to an open issue here)**

`gh` repo completion for users own repos but not others

**What is the new behavior (if this is a feature change)?**

autocomplete any public repos you want!

and an update to `gh auth`

**Additional info:**

literal magic..  🤯.

@mschrage suggested that custom did not need to be wrapped in `try..catch` and the [docs example](
https://github.com/withfig/autocomplete-tools/blob/aad28dc389b49155e8523bf589a17370a66f1f63/packages/autocomplete-types/index.d.ts#L1014-L1022)  does not have `try catch`.

@fedeci can you confirm if this is the case?

### CODE REVIEW

**Comment by ShawnCockburn** [comment]
@mschrage thanks for explaining `custom()` to me it makes so much sense now!

**Review by mschrage — CHANGES_REQUESTED** [review]
I think we will need to add a `trigger: "/"` to cause the custom generator to be reevaluated.

**Comment by ShawnCockburn** [comment]
> I think we will need to add a `trigger: "/"` to cause the custom generator to be reevaluated.

done!

**Review by loloboin — APPROVED** [review]

**Review by mschrage — APPROVED** [review]

**Review by fedeci — APPROVED** [review]
Thanks!

**Pull request merged**
