### PR TITLE
Added azure all command and subCommand

### PR DESCRIPTION
**Pull request by ikushaldave**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This will add all the azure command available in azure CLI.

**What is the current behavior? (You can also link to an open issue here)**

This part of autocompletion was missing in the fig.

**What is the new behavior (if this is a feature change)?**

This add most of azure command to fig autocompletion but have to work adding azure CLI options which is missing in this PR.

**Additional info:**

### CODE REVIEW

**Comment by mschrage** [comment]
Woah @ikushaldave! Thank you so much for this contribution. 🤩

I assume these were generated programmatically? Would you mind sharing the source code, so I can look at that rather than the generated completions. :)

**Comment by SeparateRecords** [comment]
Hi @ikushaldave - would really love if you could put up the source code for your generator, maybe as another repo similar to how @ryanccn did for https://github.com/ryanccn/ffmpeg-fig ?

It's a lot easier to review that than a 33,000 line PR 😅

**Comment by ikushaldave** [comment]
Hey @mschrage Hey Sorry I was in hospital just discharged will soon in this week a code.

**Comment by fedeci** [comment]
Thanks @ikushaldave! Hope you are fine!

**Comment by manutero** [comment]
Amazing @ikushaldave I was just looking for az-cli autocomplete!

**Comment by SeparateRecords** [comment]
@ikushaldave hope everything is okay now! Don't stress about getting this done, take whatever time you need to recover 🙂

**Comment by SeparateRecords** [comment]
Just wanted to quickly poke you @ikushaldave, hope your recovery is going well!

Do you have any progress to share with the azure CLI generator? I'd even be happy to take over this PR if you're busy 🙂

**Comment by ikushaldave** [comment]
Hey @SeparateRecords here is code that I used it look for web scrapping from azure cli reference docs. This code will not so good and readable. I thought to update code with extracting options too and optimise the code removing repetitive code.

[git@github.com:ikushaldave/web-scrapping-azure-cli.git](https://github.com/ikushaldave/web-scrapping-azure-cli)

I will complete it within upcoming days with adding options to output

**Comment by brendanfalk** [comment]
Closing this as it was never finalised. Really appreciate this awesome work however:
1. The azure CLI has changed massively since this merge
2. We need to be able to support updates to the azure CLI

**Pull request closed without merging**
