### PR TITLE
Completes `open` spec

### PR DESCRIPTION
**Pull request by bolshoytoster**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix
**What is the current behavior? (You can also link to an open issue here)**
`open`'s spec isn't complete. #872 
**What is the new behavior (if this is a feature change)?**
`open`'s spec is complete.

### CODE REVIEW

**Review by mschrage — APPROVED** [review]
This looks great @bolshoytoster! Thanks so much for contributing :)

Also are you in our [Discord community](https://fig.io/community)? I'd love to give you the contributor badge (you've definitely earned it!) 🥳

**Comment by bolshoytoster** [comment]
@mschrage I'll join, bolshoy#0648.

**Comment by mschrage** [comment]
@bolshoytoster it looks like the typecheck / linter is failing. Can you fix that? (`yarn run lint:fix`)

**Comment by bolshoytoster** [comment]
@mschrage it should be fixed now.

**Pull request merged**
