### PR TITLE
feat: add enapter cli completion spec

### PR DESCRIPTION
**Pull request by nkrasko**

### CODE REVIEW

**Comment by nkrasko** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nkrasko** [comment]
recheck

**Comment by mschrage** [comment]
Hey @nkrasko it seems like you're modifying the yarn.lock file. Can you remove this from your PR? Otherwise, the spec itself looks good and is ready to merge. :)

**Comment by nkrasko** [comment]
Hi @mschrage i've reverted yarn.lock. Thanks!

**Review by grant0417 — APPROVED** [review]

**Pull request merged**
