### PR TITLE
Brew untap spec

### LINKED ISSUE #1152: [brew] add `untap` command
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

brew

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

`brew untap` should be added.

It's used to: 
> Remove a tapped formula repository.

https://stackoverflow.com/questions/68112422/how-remove-homebrew-tap

https://docs.brew.sh/Manpage#untap---force-tap-

### PR DESCRIPTION
**Pull request by codedbyjordan**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
Spec does not exist for the untap subcommand

**What is the new behavior (if this is a feature change)?**
Adds a spec for `brew`'s `untap` subcommand

**Additional info:**
Fixes #1152

### CODE REVIEW

**Review by mschrage — APPROVED** [review]
Looks good to me! Thanks for contributing ❤️

(In the future, mind splitting out changes to different completion specs into separate PRs?)

**Comment by codedbyjordan** [comment]
> Looks good to me! Thanks for contributing ❤️
> 
> (In the future, mind splitting out changes to different completion specs into separate PRs?)

Could you elaborate? I'm a bit dumb, sorry.

**Comment by mschrage** [comment]
It's not a big deal. This PR has changes to both the `brew` spec and the `valet` spec. Ideally, only the `brew` changes would be included in this PR.

**Comment by codedbyjordan** [comment]
oh, not sure why, I only changed the brew spec.

**Comment by fedeci** [comment]
If those changes were not intentional the should likely be reverted, I am checking later :)

**Comment by codedbyjordan** [comment]
> If those changes were not intentional the should likely be reverted, I am checking later :)

I only changed the brew.ts so i’m not sure why anything else was changed, i’m sorry :/

**Comment by fedeci** [comment]
Don't worry, it happens to everyone!

**Comment by fedeci** [comment]
Found the problem, that was a previous commit you did on another PR (already merged).
Tip: before creating a new branch on top of master remember to run `git pull --rebase upstream master`.

**Comment by codedbyjordan** [comment]
Ah, got it. Thank you so much!

**Pull request merged**
