### PR TITLE
Update git spec to support gitmoji suggestions on commit message

### PR DESCRIPTION
**Pull request by yaronuliel**
close withfig/autocomplete#817

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the new behavior (if this is a feature change)?**
autocomplete for `git commit -m ` shows suggestions for standard gitmoji

https://user-images.githubusercontent.com/5229872/148439032-f846a981-bc4a-431f-95d5-ae4ab8c0c878.mov

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
I don't think we should provide these suggestions for everyone. Gitmoji is a separate feature from git and I would rather prefer a separate spec for the gitmoji cli or some kind of mechanism to detect if user has gitmoji cli installed and only in that case provide suggestions for gitmoji in git spec

**Review by mschrage — CHANGES_REQUESTED** [review]
Hey @yaronuliel! I think this is awesome but I'm not sure if this should be the default behavior in the `git` completion spec. 

Is there anyway to detect if someone is using gitmoji by running a CLI command and then we could show these suggestions? 

Perhaps by running `gitmoji --version` to see if the CLI tool is installed or by running `git log --pretty=format:%s` and checking if the last n commits start with an emoji?

**Comment by yaronuliel** [comment]
@mschrage gitmoji doesn't require any external tool, and works with all major git providers without any additional software, or tools. In my opinion it is not different from suggesting `Bugfix: {cursor}` which is also just a convention. Searching for previous gitmoji in git history is indeed an option, but it means that it won't work for new git projects (maybe we can leave the :tada: (`:tada:` which represents new project git commit, and will usually be added to first commit in a repo) available for new projects, and show the rest only if it was used

@fedeci The [gitmoji cli](https://github.com/carloscuesta/gitmoji-cli) in a utility that helps using gitmojies (as I mentioned in the issue #817 it is quite hard to remember all the possible notations, and this is what gitmoji-cli is for). Having a completion for `$ gitmoji-cli ...` will off course require a separate spec.

Anyway, I do agree that adding a config option that will allow users to switch the feature on/off is required (the big question is about the default)

**Comment by fedeci** [comment]
I think you can use [personal mixins](https://fig.io/docs/guides/personal-mixins) and we should probably work on some way to allow mixins to be shared.
WDYT @mschrage?

**Comment by mschrage** [comment]
@yaronuliel I agree with @fedeci here. This makes more sense as a [mixin](https://fig.io/docs/guides/personal-mixins) than part of the git completion spec.

I'm going to close this PR for now. But I love the idea and definitely want to find a way for you to share this with the community.

**Pull request closed without merging**
