### PR TITLE
feat(fig): add unset completion spec

### PR DESCRIPTION
**Pull request by Sam-Lara**
Added autocomplete functionality for the unset command.

### CODE REVIEW

**Comment by DarrenSeng** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sam-Lara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Frodriguez116** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fedeci** [comment]
Duplicate of #1854

**Pull request closed without merging**
