### PR TITLE
feat(ping): add Apple-only options

### PR DESCRIPTION
**Pull request by cHaLkdusT**

### CODE REVIEW

**Comment by SeparateRecords** [comment]
@fedeci thoughts on merging? These options exist on macOS but obv not linux

**Comment by fedeci** [comment]
> @fedeci thoughts on merging? These options exist on macOS but obv not linux. I'm landing more on the side of not merging until we have OS-specific options but I don't have a good reason for that... it's not like Linux users would try to use an option marked with `--apple` and go "why doesn't this work??"

I still think TODO comments are the way.
@cHaLkdusT could you add this comment to the relevant options? `// TODO(platform): apple only option`

**Comment by cHaLkdusT** [comment]
I have now added // TODO comments to the relevant options

**Review by fedeci — APPROVED** [review]
Thanks!

**Pull request merged**
