### PR TITLE
[FIG] feat: add automation to PRs

### PR DESCRIPTION
**Pull request by cstrnt**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

### CODE REVIEW

**Comment by cstrnt** [comment]
Hello @cstrnt

**Review by mattschrage — COMMENTED** [review]
Overall, everything is looking good.

How hard would it be to show `scripts` that have `postProcess` functions, in the same place.

For example, something like:
**script:** `ls -1aF`
**postProcess:**
```typescript
function (out) {
 return out.split('\n')
}
```

Rather than having separate categories. 

I don't think this is make or break, just want to get a sense of how doable this is?

**Comment by cstrnt** [comment]
The badge will start to work as soon as the PR is merged.  The current badge is broken (can't be inlined) that's why we need to use another one

Info:
- https://github.com/all-contributors/all-contributors/issues/361
- https://github.com/all-contributors/all-contributors/issues/406

**Comment by cstrnt** [comment]
Rounded images aren't possible inside a table in markdown unfortunately

**Review by mattschrage — APPROVED** [review]
Looks good to me! Excited to get this merged in :)

**Pull request merged**
