### PR TITLE
feat: (incomplete) add spec-versioning to yarn

### PR DESCRIPTION
**Pull request by EthanOrlander**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature - Spec versioning

**What is the current behavior? (You can also link to an open issue here)**
[No spec versioning](https://github.com/withfig/fig/issues/346)
**What is the new behavior (if this is a feature change)?**
Spec versioning
**Additional info:**

### CODE REVIEW

**Comment by EthanOrlander** [comment]
I don't think I have access to make this a draft. Can someone do that?

**Comment by Nutlope** [comment]
Hi @EthanOrlander! Sorry for the late reply, just wanted to say that your original issue & proposal for versioning sparked some good discussion internally. We're currently working out the best way to do versioning for specs, we'll have something out soon. Thank you so much for your thoughts! Will review this when we have a finalized versioning system in place :)

**Comment by EthanOrlander** [comment]
No need! I think I'll delete this PR and restart once y'all come up with the versioning system. I'd love to contribute to getting everything moved over & versioned (I imagine this will be a considerable effort...). Let me know where I can lend a hand 🙂

**Comment by fedeci** [comment]
@Nutlope the `remove`, `add`, etc... one?

**Comment by Nutlope** [comment]
> No need! I think I'll delete this PR and restart once y'all come up with the versioning system. I'd love to contribute to getting everything moved over & versioned (I imagine this will be a considerable effort...). Let me know where I can lend a hand 🙂

Sounds great! Thanks, Ethan will do :)

**Comment by Nutlope** [comment]
> @Nutlope the `remove`, `add`, etc... one?

Correct! We're discussing some alternate approaches

**Comment by EthanOrlander** [comment]
> > @Nutlope the `remove`, `add`, etc... one?
> 
> Correct! We're discussing some alternate approaches

I'm excited to see what you come up with!

**Pull request closed without merging**
