### PR TITLE
feat: add webpack spec

### LINKED ISSUE #1084: [webpack] missing spec
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

https://github.com/webpack/webpack-cli

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

 - Main/most often used options/subcommands are documented on webpack's [official website](https://webpack.js.org/api/cli/)
 - All options/subcommands are documented under the [`OPTIONS.md`](https://github.com/webpack/webpack-cli/blob/master/OPTIONS.md) file of the `webpack/webpack-cli`, which also shows when running `webpack --help=verbose`

----
In total, the webpack CLI provides almost *1,000* options! So, I wrote a script to parse the help manual at`OPTIONS.md` to help generate some JSON for scaffolding (since I didn't want to manually convert it all by hand): https://gist.github.com/neoncitylights/22cc1e97d19e11c0eca3980ec31993ec

There is also a [TypeScript playground](https://tsplay.dev/NVa2Zw) available if you'd like to run it!

I also just recently realized that Fig's type definitions are also public (!), so I'm currently working on to migrate the types and do a slight refactor, then submit for PR when ready.

If it would be easier to start with for PR reviewing, I can also submit a PR with just the main options documented on webpack's official website, and expand from there in a followup PR.

### PR DESCRIPTION
**Pull request by neoncitylights**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds a new spec for the webpack CLI, which is an open-source bundler for web development.

**What is the current behavior? (You can also link to an open issue here)**
Fig does not provide autocomplete for `webpack`.

**What is the new behavior (if this is a feature change)?**
There is functional autocomplete for `webpack`:
image

**Additional info:**
Fixes #1084. The webpack-cli provides almost 1000 options (exactly 957). This spec was mostly generated with a [script I wrote](https://github.com/neoncitylights/cli-help-parser). It parses part of the the [`OPTION.md`](https://github.com/webpack/webpack-cli/blob/master/OPTIONS.md) file in webpack/webpack-cli, and the subcommands I had manually added in.

First, it creates an AST. After, it does some post-processing, which iterates through each `Fig.Option` by scanning the description. It uses some basic heuristics to check for some more information:
 - If the sentence contains the keyword deprecated, it will mark it as deprecated via `deprecated: true`.
 - **Folders**: If the sentence contains the keywords `"directory"` or `"folder"`, and the option accepts an argument, it will add `"folders"` to the `template` property.
 - **Filepaths**: If the sentence contains the keywords `"filename"`, and the option accepts an argument, it will add `"filepaths"` to the `template` property.

Feedback welcome! Thanks a bunch, this tool is really great.

### CODE REVIEW

**Comment by neoncitylights** [comment]
So, I just discovered that https://github.com/withfig/cli-help-parser exists, haha. I didn't know about it until just now! Oops.

I'm not sure where to go from here in terms of a CLI help parser now that there's two. If there's any interest in the parser I wrote, I would be willing to help work on making it be more generic and adapt for more tools. I'd also love to contribute to the Fig repo as well if it's accepting contributions! Thanks again.

**Review by fedeci — APPROVED** [review]
Love this PR! Will make my life so much easier when I'm using webpack😄

**Comment by fedeci** [comment]
> I'm not sure where to go from here in terms of a CLI help parser now that there's two. If there's any interest in the parser I wrote, I would be willing to help work on making it be more generic and adapt for more tools. 

That would be great! https://github.com/withfig/cli-help-parser was written some time ago and probably is missing some properties we have added recently so yours is probably more accurate.

> I'd also love to contribute to the Fig repo as well if it's accepting contributions! Thanks again.

If by "Fig repo" you mean this repo we would love other contributions, if you are interested in going deeper in the codebase you should get a call with @brendanfalk and see https://fig.io/jobs!

**Comment by neoncitylights** [comment]
> > I'd also love to contribute to the Fig repo as well if it's accepting contributions! Thanks again.
> 
> If by "Fig repo" you mean this repo we would love other contributions, if you are interested in going deeper in the codebase you should get a call with @brendanfalk and see https://fig.io/jobs!

Hi, thank you! I'm looking forward to applying to the company within the next few days. :)

**Pull request merged**
