### PR TITLE
feat: add mix completion spec

### PR DESCRIPTION
**Pull request by benvp**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Add completion spec for `mix` elixir build tool.

### CODE REVIEW

**Review by fedeci — COMMENTED** [review]
Partial duplicate of #496 but here we have generators that look good. We can wait until that gets merged and then rebase this one on top of it.

**Comment by QuiiBz** [comment]
Just reviewed #496, agree with @fedeci. Let's wait to merge #486 and then add the generator from this PR!

**Comment by benvp** [comment]
done, I also fixed the comman `pp` which has been added. This subcommand does not exist.

**Review by QuiiBz — APPROVED** [review]
LGTM, thanks a lot for this really cool PR!

**Pull request merged**
