### PR TITLE
feat: add Okta CLI spec

### PR DESCRIPTION
**Pull request by alisaduncan**
The [Okta CLI](https://cli.okta.com/) is a tool to manage [Okta](https://www.okta.com/) identity management applications & organizations.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
`okta` commands are currently not-supported

**What is the new behavior (if this is a feature change)?**
Autocomplete and documentation to help guide developers using the `okta` CLI

**Additional info:**

### CODE REVIEW

**Comment by alisaduncan** [comment]
Requested change applied and branch rebased

**Review by mschrage — APPROVED** [review]
Thank you so much for contributing @alisaduncan!! Merging in now ✨🥳

### Next steps
💬 **If you are in our [Discord](https://fig.io/community)**: let me know your username so I can give you the 'Contributor' badge!

🐥 **If you have a Twitter**: tweet that `okta` is now supported and we'll retweet from the [@fig](https://twitter.com/fig) account :)

🛠 **Are you interested in being a codeowner?** You'll be pinged to review any future PRs for the `okta` completion spec.

**Comment by mschrage** [comment]
Also do you think it would be possible to add a screenshot of the okta completions to [this page](https://cli.okta.com/manual/) along with a link to [fig.io](https://fig.io)?

**Comment by alisaduncan** [comment]
@mschrage I think so. I will work on this. We'll definitely want to share how helpful the okta completions are using Fig. 😀

Thanks for making this contribution such an easy and fun experience! 🎉

**Comment by mschrage** [comment]
That would be amazing! Thanks for the kind words :)

**Pull request merged**
