### PR TITLE
feat: add spec for shadcn-ui

### PR DESCRIPTION
**Pull request by neo773**
This PR adds spec for [shadcn-ui cli](https://ui.shadcn.com/)

https://github.com/withfig/autocomplete/assets/62795688/78a35e22-009d-47c3-9e8e-2a378357f2cb

### CODE REVIEW

**Comment by grant0417** [comment]
Hey, this looks good but can you remove the `yarn.lock` changes?

**Comment by neo773** [comment]
@grant0417 Done, revered the `yarn.lock` changes.

**Comment by mschrage** [comment]
Hmm looks like there are still conflicts w/ yarn.lock. Mind fixing those so we can get this merged in? @neo773

**Comment by neo773** [comment]
Well, at this point I have no idea how to salvage this

**Comment by grant0417** [comment]
Just run `git checkout master -- yarn.lock`

**Comment by neo773** [comment]
That didn't work had to do checkout from upstream/master, anyways can you review it now?

**Review by mschrage — APPROVED** [review]

**Pull request merged**
