### PR TITLE
feat: add initial ffmpeg autocomplete

### PR DESCRIPTION
**Pull request by ryanccn**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the new behavior (if this is a feature change)?**

added `ffmpeg` autocompletion

**Additional info:**

Something concerning is, a Deno codebase in a Node one doesn't work too well. Might consider moving the script to Node?

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
Thanks! The spec looks really good but the `ffmpeg/` folder should not be added to this repo.
Since it seems a lot of work, why don't you try to push the autogenerator directly to the ffmpeg repo? Please ping me if you open a PR or an issue there!

**Comment by ryanccn** [comment]
I currently have a private repo with the automation script, so it could be just open sourced?

**Comment by fedeci** [comment]
> I currently have a private repo with the automation script, so it could be just open sourced?

In my opinion yes!

**Comment by ryanccn** [comment]
> > I currently have a private repo with the automation script, so it could be just open sourced?
> 
> In my opinion yes! Especially if you succeed in merging the automation script in the ffmpeg organization. You will get all the benefits of open source!

How do I merge the script into the ffmpeg organization?

**Comment by ryanccn** [comment]
@fedeci

**Comment by fedeci** [comment]
> > > I currently have a private repo with the automation script, so it could be just open sourced?
> 
> > 
> 
> > In my opinion yes! Especially if you succeed in merging the automation script in the ffmpeg organization. You will get all the benefits of open source!
> 
> 
> 
> How do I merge the script into the ffmpeg organization?

I have no idea, you should open an issue over there to see if maintainers are willing to merge it, if they are they will help you to do that.

**Comment by mschrage** [comment]
@ryanccn either way, it would be awesome if you can make the source code public so that others can use it / rerun it for updates.

**Comment by fedeci** [comment]
Eventually submit a PR to this repo adding a comment to the top of the ffmpeg.ts file with the link of your repo so that you get credits for the work you did and anyone can run the generator.

**Comment by ryanccn** [comment]
Sure!

**Comment by ryanccn** [comment]
Opened PR #902

**Comment by ryanccn** [comment]
Say, I could use a GitHub Action to periodically generate and if there's any difference with the spec in this repo, automatically create a PR. That wouldn't require any manual actions for updates in ffmpeg.

**Pull request merged**
