### PR TITLE
feat: add flyctl spec

### PR DESCRIPTION
**Pull request by BogDAAAMN**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Added completion specs for [flyctl](https://fly.io/docs/flyctl/) CLI, the command-line interface for fly.io! 

It is auto-generated with the [`github.com/withfig/autocomplete-tools/packages/cobra`](https://github.com/withfig/autocomplete-tools/blob/main/packages/cobra/README.md) package. With the help of amazing @davidalpert we found a work-around and made the package to work with the current [`flyctl` cobra implementation](https://github.com/superfly/flyctl). You can see the implementation here https://github.com/BogDAAAMN/flyctl/commit/c0f338a6f3c59acc8286a8c82836fc2e73124b6f.

I am not familiar enough with Go to propose a better implementation or perhaps a GitHub Action, although I would love to try better! Anyhow I'm pinging the fly.io folks here, maybe there's something they might consider it ever. I'd love to try more. @michaeldwan @codepope @ThisIsRahmat @rugwirobaker

**Additional info:**

Added the following generators:
- `template: "filepaths"` for all the `config` arguments
- Generate the apps and orgs using the `flyctl list apps` command. It changes the icon based on `status`
  https://github.com/withfig/autocomplete/blob/72c5328f330775ce3e4954d918e26eb0b147b63a/src/flyctl.ts#L9-L26

### CODE REVIEW

**Comment by fedeci** [comment]
> I am not familiar enough with Go to propose a better implementation or perhaps a GitHub Action, although I would love to try better! Anyhow I'm pinging the fly.io folks here, maybe there's something they might consider it ever. I'd love to try more. @michaeldwan @codepope @ThisIsRahmat @rugwirobaker

**Comment by fedeci** [comment]
And currently we have a GH action to automate pushes to this repo, check out https://fig.io/docs/guides/integrating/push-to-autocomplete-action!

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by BogDAAAMN** [comment]
Thanks @fedeci 🙌🏼

**Comment by jsierles** [comment]
This is great! Thanks for working on this.

I noticed that completion only works with `flyctl` and not with the symlinked `fly`. Is there a way to make it work with both?

**Comment by fedeci** [comment]
@BogDAAAMN you can to import the spec in a new file named `fly.ts`, change the name and directly export it.

```ts
import spec from './flyctl'
export default {
  ...spec,
  name: 'fly',
}:
```

**Comment by BogDAAAMN** [comment]
Thank you @fedeci, pushed to #1207. 

Will the generators working as well, although they're not explicitly exported (`const flyAppsGenerator: Fig.Generator = {`)? They're working in my terminal, but just making sure I'm doing the best practices 🤔

**Comment by fedeci** [comment]
They are, js imports are resolved through files!

**Pull request merged**
