### PR TITLE
feat: add `wasm-pack` spec

### LINKED ISSUE #1074: [wasm-pack] missing spec
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

https://github.com/rustwasm/wasm-pack

### Which statement makes the most sense?

This completion spec does not exist

### Issue Details

This tool is created by the Rust and WebAssembly Working Group to aid in the workflow of easily generating WebAssembly packages to publish to NPM.

Reference: https://rustwasm.github.io/docs/wasm-pack/commands/index.html

### PR DESCRIPTION
**Pull request by neoncitylights**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds a new spec 
**What is the current behavior? (You can also link to an open issue here)**
There is no Fig spec for the `wasm-pack` CLI tool.

**What is the new behavior (if this is a feature change)?**
image

**Additional info:**
Fixes #1074.

### CODE REVIEW

**Review by mschrage — APPROVED** [review]
This looks great! Thanks so much for these contributions @neoncitylights.

(One small thing... going forward can you split out completion specs into separate PRs? Just makes everything easier to review. Thanks!)

**Comment by neoncitylights** [comment]
Oh, my I accidentally committed both into one PR. Yes, sounds good!

**Comment by mschrage** [comment]
Also I just saw your CLI help text parser @neoncitylights. Honestly super impressive. Are you in our [Discord](https://fig.io/community) community? :)

**Comment by neoncitylights** [comment]
Thank you very much! Yes, I'm Samantha (starryflies#1436) on Discord. 😄

**Pull request merged**
