### PR TITLE
feat: add swagger-typescript-api completion spec

### PR DESCRIPTION
**Pull request by tmwrnr**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
Adds a new spec for [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api)

**Additional info:**

### CODE REVIEW

**Comment by tmwrnr** [comment]
@fedeci Thanks for the approval, but I am not allowed to merge as far as I can see. Or am I missing something?

**Review by fedeci — APPROVED** [review]

**Comment by fedeci** [comment]
recheck

**Comment by tmwrnr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tmwrnr** [comment]
recheck

**Comment by fedeci** [comment]
Thanks!

**Pull request merged**
