### PR TITLE
feat: add sl completion spec

### PR DESCRIPTION
**Pull request by mbd-s**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature (adds a completion spec for `sl`),

**What is the current behavior? (You can also link to an open issue here)**
There is no currently available completion spec for `sl`.

**What is the new behavior (if this is a feature change)?**
A completion spec for `sl` has been added.

### CODE REVIEW

**Comment by mbd-s** [comment]
Sorry about the duplicate PRs, I got in a git muddle with the [first one](https://github.com/withfig/autocomplete/pull/1704) after renaming the default branch from `master` to `main`

**Comment by grant0417** [comment]
Not to ruin your PR but a little concerned about the naming conflict now with https://sapling-scm.com

**Comment by mbd-s** [comment]
> Not to ruin your PR but a little concerned about the naming conflict now with https://sapling-scm.com

Fair enough. I'll close the PR since I don't see a way to resolve the conflict.

**Comment by fedeci** [comment]
@mbd-s right now there is no quick way to solve this issue but we will work on it in the (possibly near) future, can you keep this PR open, please?

**Comment by mbd-s** [comment]
@fedeci Thanks for the feedback. I'll look into leveraging `generateSpec` to load the right spec dynamically!

**Comment by mbd-s** [comment]
@fedeci Thanks for the feedback. I'll look into leveraging `generateSpec` to load the right spec dynamically!

**Comment by fedeci** [comment]
Great! Ping me if you need help!

**Comment by fedeci** [comment]
recheck

**Comment by mbd-s** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by fedeci** [comment]
I'll add the sapling spec and face the generate spec issue!

**Pull request merged**
