### PR TITLE
feat: add deta completion spec

### PR DESCRIPTION
**Pull request by BogDAAAMN**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Creating the specs for the [Deta CLI](https://www.deta.sh/). The references follow the [Deta CLI Docs](https://docs.deta.sh/docs/cli/commands) on the latest version [v1.3.0-deta](https://docs.deta.sh/docs/cli/releases#v130-beta). The descriptions of the commands are also extracted from the docs. 

**Additional info:**
Also pinging the @deta folks here in case of review @abdelhai @aavshr @rohanshiva @rabingaire @xeust

### CODE REVIEW

**Comment by QuiiBz** [comment]
Looks like the linter is failing, could you run the `lint:fix` script?

**Comment by BogDAAAMN** [comment]
@QuiiBz hmm, strange it didn't yield any linter error on the first try. Ran the `lint:fix` and pushed the fixes. Thanks!!

**Comment by QuiiBz** [comment]
> @QuiiBz hmm, strange it didn't yield any linter error on the first try. Ran the `lint:fix` and pushed the fixes. Thanks!!

That was due to an upstream error that is now fixed, apologise for the issue.

**Review by QuiiBz — APPROVED** [review]
LGTM, thanks a lot  🎉

**Pull request merged**
