### PR TITLE
feat(cxcli): update spec

### PR DESCRIPTION
**Pull request by xavidop**
PR generated automatically from push-to-fig-autocomplete-action.

### CODE REVIEW

**Comment by xavidop** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by grant0417** [comment]
Hey @xavidop looks like there is an issue with the spec, I have an update to the `@fig/complete-commander` package I will publish which should fix it https://github.com/withfig/autocomplete-tools/pull/156

**Comment by xavidop** [comment]
@grant0417 perfect! what should I do on my side?

**Comment by grant0417** [comment]
I have published `@fig/complete-commander@3.2.0`, just update to that version of the integration and it should fix the lint issues.

**Pull request closed without merging**
