### PR TITLE
feat(go): workspace spec

### PR DESCRIPTION
**Pull request by beyazit**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
adds completion spec for the Go [workspaces](https://go.dev/doc/tutorial/workspaces)

### CODE REVIEW

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by fedeci** [comment]
recheck

**Comment by beyazit** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/withfig/autocomplete/blob/master/cla/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by fedeci** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/withfig/autocomplete/blob/master/cla/cla.md?rgh-link-date=2022-12-07T20%3A21%3A34Z) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

@beyazit since a couple days we ask contributors to sign a CLA, can you please sign read and "sign" this so I can get this PR merged ASAP? Thanks!

**Comment by beyazit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by fedeci — APPROVED** [review]
Thanks again!

**Pull request merged**
