### PR TITLE
feat(remotion): update autocomplete for 3.1

### PR DESCRIPTION
**Pull request by JonnyBurger**
For Remotion CLI, adding flags that we recently introduced:

- `--concurrency-per-lambda` flag
- `--quiet` flag
- `--number-of-gif-loops` and `--every-nth-frame` flag
- The output name parameter is now optional.

My plan is to always batch together a few changes and send them from time to time!

### CODE REVIEW

**Comment by fedeci** [comment]
@JonnyBurger are you using some CLI framework.

**Comment by JonnyBurger** [comment]
nope. i update it manually!

**Review by fedeci — APPROVED** [review]
Thanks!

**Review by SeparateRecords — APPROVED** [review]
Nice! Easy update.

@fedeci looks like internally the CLI is built on minimist

**Comment by fedeci** [comment]
Synced review😄

**Comment by JonnyBurger** [comment]
Generating a Fig scheme from our CLI parser would be interesting as well, I'll explore that in the future probably!

**Pull request merged**
