### PR TITLE
feat: implement `az` spec

### PR DESCRIPTION
**Pull request by cpendery**
Implements the azure command line via a diff versioned spec, picking up the work started in #866. The code is generated via my [autocomplete-az](https://github.com/cpendery/autocomplete-az) repo via `npx autocomplete-az`. 

Due to `az` cli surface changes introduced in every minor version change, as reflected by the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md), I thought it best to add new specs for each minor version, but happy for feedback if there is a better approach or any concerns with this

### CODE REVIEW

**Comment by cpendery** [comment]
Additionally, I'm unable to test the spec as I don't have a macbook, so if a maintainer could double check that the way I setup the `loadSpec` actually works for a versioned spec, that would be super helpful

**Comment by cpendery** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mschrage** [comment]
Thank you so much for this massive contribution @cpendery! I will test locally to confirm `loadSpec` works as expected.

**Comment by mschrage** [comment]
@cpendery Also can you resolve the linting errors and the type checking errors?

**Comment by cpendery** [comment]
> @cpendery Also can you resolve the linting errors and the type checking errors?

@mschrage happy to fix the linting errors, but it looks like the PR makes the type checker run out of memory, any advice on how to resolve that?

**Comment by cpendery** [comment]
Also @mschrage does doing the version specs like this make sense for every minor release? I don't want to bloat the repo unnecessarily. Would it be better to just use generateSpec with versions when things change?

**Comment by grant0417** [comment]
Fixed some small issues with this but this looks great! Thanks so much for the contrib!

**Pull request merged**
