### PR TITLE
Update support for yarn workspace

### LINKED ISSUE #880: `yarn workspace` does not support complete package `workspaces` specification syntax
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

yarn

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

It looks like support for `yarn workspace` was most recently enhanced in [this PR](https://github.com/withfig/autocomplete/pull/678) however it does not yet support the complete specification. It correctly generates workspace names if the root `package.json` uses this format:

```json
{
  "workspaces": [
    "packages/*",
    "plugins/*",
    "sites/*"
  ]
}
```
...but it does not pick up workspace names if the root `package.json` is using the more complex format here:
```json
{
  "workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "sites/*"
    ],
    "nohoist": ["**/react-native", "**/react-native/**"]
  }
}
```

### PR DESCRIPTION
**Pull request by bolshoytoster**
Should fix #880

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix
**What is the current behavior? (You can also link to an open issue here)**
 `yarn workspace` does not support complete package workspaces specification syntax (#880)
**What is the new behavior (if this is a feature change)?**
It now recurses through the `package.json` file, instead of just reading the top level.

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
We decided to parse the `package.json` because yarn@2 has renamed `yarn workspaces info` to `yarn workspaces list`. Furthermore the output of the two commands is not the same and for yarn@2 we do not get any info about the package name and we would still need to parse it from the `package.json`.

**Comment by fedeci** [comment]
I am not even sure if yarn@3 changed something again.

**Comment by bolshoytoster** [comment]
@fedeci so would my [first approach](https://github.com/withfig/autocomplete/pull/887/commits/75098ac5dbcbda627fd1fbafc2defb3c90dd10e5#diff-7bbad50579e0e812ea35da837d8fd6075ebab353dd246092def2d178ef41de74) of recursing over the object work or does it have to be something different?

**Comment by lunelson** [comment]
@fedeci would it not also be possible to check the `yarn` version first, and then do `yarn workspaces info` or `yarn workspaces list` based on that output? I'm just thinking it's more robust to treat yarn itself as the source of truth concerning the configured workspaces, rather than re-build the parsing logic 🤷‍♂️

**Comment by bolshoytoster** [comment]
> @fedeci would it not also be possible to check the `yarn` version first, and then do `yarn workspaces info` or `yarn workspaces list` based on that output? I'm just thinking it's more robust to treat yarn itself as the source of truth concerning the configured workspaces, rather than re-build the parsing logic 🤷‍♂️

There's also [this documentation](https://fig.io/docs/handbook/versioning-completion-specs) that explains it.

**Comment by fedeci** [comment]
> @fedeci would it not also be possible to check the `yarn` version first, and then do `yarn workspaces info` or `yarn workspaces list` based on that output? I'm just thinking it's more robust to treat yarn itself as the source of truth concerning the configured workspaces, rather than re-build the parsing logic 🤷‍♂️

It is possible just because `yarn` is caching the package names and paths.
However that would not reduce the complexity of the code when runned because we would still need to parse all the package.json to retrieve scripts resulting in a small delay when running `yarn workspace[space]` (currently we have this delay).
I think we can cancel the delay using yarn info/list along with `generateSpec` to generate the scripts of each package only when that package is run (`yarn workspace @withfig/autocomplete-tools[space]`).

**Comment by fedeci** [comment]
> > @fedeci would it not also be possible to check the `yarn` version first, and then do `yarn workspaces info` or `yarn workspaces list` based on that output? I'm just thinking it's more robust to treat yarn itself as the source of truth concerning the configured workspaces, rather than re-build the parsing logic 🤷‍♂️
> 
> There's also [this documentation](https://fig.io/docs/handbook/versioning-completion-specs) that explains it.

I would still keep the current structure as long as there are no bigger changes to subcommands

**Comment by mschrage** [comment]
@fedeci can this be merged as is or should we close it? @bolshoytoster has a spec for `gpg` that is waiting on this PR. #890

**Comment by fedeci** [comment]
@bolshoytoster you can have multiple PRs open. You need to use a new branch, as I assume you are doing, for the new PR code, then when you create the new PR you need to select as your HEAD the correct branch. We don't have to close this one.

**Comment by bolshoytoster** [comment]
@fedeci I do have a branch for it, however the branch also has the commits for this PR. Is there an easy way to remove commits from a branch?

**Comment by fedeci** [comment]
You can drop some commits from a branch using interactive git rebase. Or you can create a new branch on top of the correct `master` (the upstream one) and cherry pick the commits you want.

**Comment by bolshoytoster** [comment]
@fedeci thank you, I've rebased it and I'm opening a PR.

Can we get this PR merged as well at some point? What needs to be changed.

**Comment by fedeci** [comment]
> It is possible just because `yarn` is caching the package names and paths. However that would not reduce the complexity of the code when runned because we would still need to parse all the package.json to retrieve scripts resulting in a small delay when running `yarn workspace[space]` (currently we have this delay). I think we can cancel the delay using yarn info/list along with `generateSpec` to generate the scripts of each package only when that package is run (`yarn workspace @withfig/autocomplete-tools[space]`).

@bolshoytoster these are my considerations concerning this PR

**Comment by elevatebart** [comment]
I would love this update. 
I have been working on a PR myself to make it work.

Is there remaining work to be done to optimize the autocomplete?
@fedeci Should this be published as a placeholder and optimized later?

**Comment by fedeci** [comment]
I think @bolshoytoster closed this because no longer intends to work on this. Am I correct?
@elevatebart does your PR implements what I wrote above? If not I can work on it later.

**Pull request closed without merging**
